name: muniapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.17.0
  get: ^4.6.6
  get_storage: ^2.1.1
  http: ^1.2.2
  pull_to_refresh: ^2.0.0  # para el pull to refresh samartrefresh
  loading_animation_widget: ^1.3.0  # para la animacion de cargando
  shimmer: ^3.0.0
  buttons_tabbar: ^1.3.15 # estilo boton para los TabControllers  
  geolocator: ^13.0.2 # para la geolocalizacion
  geocoding: ^3.0.0 # para la geolocalizacion
  fluttertoast: ^8.2.10 # para el toast
  dropdown_button2: ^2.3.9
  mapbox_maps_flutter: ^2.5.1 # para el mapa
  url_launcher: ^6.3.1
  firebase_core: ^3.10.1
  firebase_messaging: ^15.2.1
  flutter_local_notifications: ^18.0.1
  # flutter_mapbox_navigation:
  #   git:
  #     url: https://github.com/codewithdarkwa/flutter_mapbox_navigation
  #     ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/img/
